$sim
P0 = 0
do
   P0 = 0
   P0.0 = 1
   waitms 50
   P0 = 0
   P0.1 = 1
   waitms 50
   P0 = 0
   P0.2 = 1
   waitms 50
   P0 = 0
   P0.3 = 1
   waitms 50
   P0 = 0
   P0.4 = 1
   waitms 50
   P0 = 0
   P0.5 = 1
   waitms 50
   P0 = 0
   P0.6 = 1
   waitms 50
   P0 = 0
   P0.7 = 1
   waitms 50
   P0 = 0
   P0.6 = 1
   waitms 50
   P0 = 0
   P0.5 = 1
   waitms 50
   P0 = 0
   P0.4 = 1
   waitms 50
   P0 = 0
   P0.3 = 1
   waitms 50
   P0 = 0
   P0.2 = 1
   waitms 50
   P0 = 0
   P0.1 = 1
   waitms 50
   P0 = 0  
loop
end